export const Users = [
    {
        id: 1,
        firstName: 'Helen',
        lastName: 'Gilbert',
        phone: '+1 415 670 90 34',
        country: 'Belarus',
        email: 'h.gilbert@akveo.com',
        password: '123456',
        newPassword: '12345678',
        confirmPassword: '12345678',
        postCount: 86,
        followersCount: 22102,
        followingCount: 536,
    },
    {
        id: 2,
        firstName: 'Emilie',
        lastName: 'McDiarmid',
        email: 'emcdiarmid1@yale.edu',
        country: 'China',
        password: 'YyKgJ8A3b4b',
        newPassword: 'DpCRPYW7Fgy',
        confirmPassword: 'DpCRPYW7Fgy',
        postCount: 95,
        phone: '86-(261)670-4133',
        followingCount: 975,
        followersCount: 1703,
    },
    {
        id: 3,
        firstName: 'Sandra',
        lastName: 'Paver',
        email: 'spaver2@ox.ac.uk',
        country: 'Greece',
        password: '0BCeHRlt84Zo',
        newPassword: '61BaifSE20w',
        confirmPassword: '61BaifSE20w',
        postCount: 60,
        phone: '30-(524)246-5851',
        followingCount: 736,
        followersCount: 1534,
    },
    {
        id: 4,
        firstName: 'Nancy',
        lastName: 'O\'Crevan',
        email: 'nocrevan3@zimbio.com',
        country: 'China',
        password: 'W0NxvHo2C',
        newPassword: 'vj4ueTKK',
        confirmPassword: 'vj4ueTKK',
        postCount: 78,
        phone: '86-(499)721-5796',
        followingCount: 86,
        followersCount: 3303,
    },
    {
        id: 5,
        firstName: 'Clayton',
        lastName: 'O\'Mullaney',
        email: 'cmullaney4@tripadvisor.com',
        country: 'Philippines',
        password: 'ZlzECwoN',
        newPassword: 'N9l5KLpBW',
        confirmPassword: 'N9l5KLpBW',
        postCount: 37,
        phone: '63-(210)188-9126',
        followingCount: 745,
        followersCount: 2703,
    },
];
export default Users;